spring.application.name=meu-imovel
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_imovel
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

spring.jpa.hibernate.ddl-auto=validate
#Help to identify if the tables are in the db
spring.jpa.show-sql=true
spring.flyway.enabled=true