CREATE TABLE proprietario
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id     INTEGER      NOT NULL,
    tipo_documento VARCHAR(4)   NOT NULL,
    documento      VARCHAR(14)  NOT NULL,
    nome           VARCHAR(150) NOT NULL,
    telefone       VARCHAR(20)  NOT NULL,
    email          VARCHAR(255) NOT NULL,
    observacoes    TEXT,

    CONSTRAINT fk_proprietario_empresa
        FOREIGN KEY (empresa_id)
            REFERENCES empresa (id),
    CONSTRAINT uq_proprietario_empresa_documento
        UNIQUE (empresa_id, documento),
    CONSTRAINT ck_proprietario_documento_tamanho
        CHECK (
            (tipo_documento = 'CPF' AND length(documento) = 11)
                OR
            (tipo_documento = 'CNPJ' AND length(documento) = 14)
            )
);